### PR TITLE
Code-wise rebranding of Elrond to MultiversX

### PR DESCRIPTION
**Pull request by andreibancioiu**
## Description

[`Elrond` is now `MultiversX`](https://twitter.com/beniaminmincu/status/1588162448103612416).

This PR applies code-wise renaming, as a follow-up of https://github.com/trustwallet/wallet-core/pull/2862.

Currently, the following file does not exist:

```
https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/multiversx/info/logo.png
```

Instead, it's available at the old path:

```
https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/elrond/info/logo.png
```

## Checklist

- [ ] Create pull request as draft initially, unless its complete.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by Milerius — DISMISSED** [review]
DisplayName can be removed from registry.json

**Review by catenocrypt — DISMISSED** [review]

**Comment by catenocrypt** [comment]
Apparently, the Elro^H^H^H^HMultiversX team really want to purge the Elrond name 🤔   Approved

**Comment by hewigovens** [comment]
This is actually is a breaking change, need to duplicate assets folder because `id` changed from `elrond` to a new value, also need to duplicate this https://github.com/trustwallet/go-primitives/blob/master/coin/coins.yml#L394

**Comment by hewigovens** [comment]
@andreibancioiu can we keep the `id` as `elrond` to avoid other breaking changes?

**Comment by andreibancioiu** [comment]
> @andreibancioiu can we keep the `id` as `elrond` to avoid other breaking changes?

@hewigovens, thank you :pray: 

I am applying this now. It seems that reverting the ID would only need reverting the name of `HRP_MULTIVERSX`, in addition.

**Review by hewigovens — APPROVED** [review]

**Comment by hewigovens** [comment]
@Milerius can you add migration guide to release notes next time? need to change protobuf model name in iOS and Android app

**Review by Milerius — APPROVED** [review]

**Pull request merged**
