### PR TITLE
[Solana]: Move Solana blockchain to Rust

### PR DESCRIPTION
**Pull request by satoshiotomakan**
## Description

Move Solana blockchain to Rust, remove legacy C++ implementation.

## How to test

Run Rust, C++, iOS, Android tests

## Checklist

- [x] Implement existing signing features from C++ to Rust
- [x] Add support for direct signing (using `RawMessage` in `Solana.proto`)
- [x] Implement preimage hashing and compiling in Rust
- [x] Implement `tw_solana_address_default_token_address`
- [x] Remove C++ implementation except `TWSolanaAddressDefaultTokenAddress`
- [x] Replace existing `TWSolanaAddressDefaultTokenAddress` implementation with `tw_solana_address_default_token_address`
- [x] Add a `TWTransactionDeserialize` FFI to deserialize transactions from a byte representation to a `Proto::SigningInput`.
- [x] Add support versioned transaction signing through WalletConnect V2

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Comment by satoshiotomakan** [comment]
Hi @CriesofCarrots, could you please take a look at the PR?

**Comment by Milerius** [comment]
Hey @CriesofCarrots we are moving our Solana C++ implementation to Rust, would like to know if u are keen to take a look on this one as u wrote the initial implementation and maybe give few hints/advice!

**Review by lamafab — APPROVED** [review]

**Comment by CriesofCarrots** [comment]
Yes, I'm up for taking a look. Might be next week, though.

**Comment by satoshiotomakan** [comment]
Hey @CriesofCarrots, thank you, look forward to your review!

**Review by Milerius — APPROVED** [review]

**Pull request merged**
