### PR TITLE
[TestOnly] #1458 -> Removed GlobalScope.launch for running tests

### PR DESCRIPTION
**Pull request by sharish**
## Description
Fixed the test as reported in #1548

## Testing instructions
`tools/android-test`

### CODE REVIEW

**Comment by hewigovens** [comment]
This test tries to run in multi threads environment, we should report failure from child threads somehow

**Comment by vcoolish** [comment]
Try this @sharish 

```kotlin
    @Test
    fun testDeriveAddressesFromPhrase() = runBlocking {
        val wallet = HDWallet("shoot island position soft burden budget tooth cruel issue economy destroy above", "")

        val scope = CoroutineScope(Dispatchers.IO)
        val jobs = mutableListOf<Deferred<kotlin.Unit>>()
        for (i in 0..4) {
            CoinType.values().forEach { coin ->
                val job = scope.async {
                    val privateKey = wallet.getKeyForCoin(coin)
                    val address = coin.deriveAddress(privateKey)
                    runDerivationChecks(coin, address)
                }
                jobs.add(job)
            }
        }
        jobs.forEach { it.await() }
    }
```

**Comment by sharish** [comment]
@vcoolish : Works great.  Just curious why are we repeating the tests on 5 threads (`for (i in 0..4)`) . Wouldn't it run quicker if the threads pick the coins in mutually exclusive manner?

Eg: Thread 1 -> Coin.ETHEREUM, Thread 2 -> Coin.BINANCE etc

**Comment by vcoolish** [comment]
> @vcoolish : Works great. Just curious why are we repeating the tests on 5 threads (`for (i in 0..4)`) . Wouldn't it run quicker if the threads pick the coins in mutually exclusive manner?
> 
> Eg: Thread 1 -> Coin.ETHEREUM, Thread 2 -> Coin.BINANCE etc

We need to be sure that nothing crashes when run multiple tasks in parallel
Even better if we don't await and just launch right in. Please apply this code

```kotlin
    @OptIn(InternalCoroutinesApi::class)
    object TestScheduler : ExperimentalCoroutineDispatcher() {
        val IO = blocking(32)
    }

    @Test
    fun testDeriveAddressesFromPhrase() = runBlocking {
        val wallet = HDWallet("shoot island position soft burden budget tooth cruel issue economy destroy above", "")

        val scope = CoroutineScope(Dispatchers.IO)
        for (i in 0..4) {
            scope.launch {
                CoinType.values().forEach { coin ->
                    launch(TestScheduler.IO) {
                        val privateKey = wallet.getKeyForCoin(coin)
                        val address = coin.deriveAddress(privateKey)
                        runDerivationChecks(coin, address)
                    }
                }
            }
        }
    }
```

**Comment by sharish** [comment]
> Even better if we don't await and just launch right in. Please apply this code

This do not work and end up being the same as reported in #1458. We need to await till the threads are done.

**Comment by catenocrypt** [comment]
Main thread has to wait for spawned thread to finish.  Swift and C++ multithreaded tests also work that way.

**Review by hewigovens — APPROVED** [review]
lgtm

**Review by vcoolish — APPROVED** [review]

**Review by catenocrypt — APPROVED** [review]

**Review by vikmeup — APPROVED** [review]

**Pull request merged**
