### PR TITLE
Include required missing headers to compile under Visual Studio

### PR DESCRIPTION
**Pull request by kaetemi**
Got it building under VS on Windows.

Still cleaning things up, so I'll just be doing pull requests one at a time for changes that are clean.

### CODE REVIEW

**Comment by hewigovens** [comment]
What windows / vs version are you using, need to check how to setup CI for windows build later

**Comment by kaetemi** [comment]
Visual Studio 2022 RC 3 on Windows 10

Writing some scripts to automate it as well.

**Comment by hewigovens** [comment]
Take a look at https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md, what else do you install to build?

**Comment by kaetemi** [comment]
So far no additional requirements. Porting the bash scripts to powershell.

**Review by hewigovens — APPROVED** [review]

**Review by catenocrypt — APPROVED** [review]

**Pull request merged**
