### PR TITLE
[Improvements]: Upgrade to c++20

### LINKED ISSUE #2359: Update to macOS-12 for iOS / Android CI
From `macos-11` to `macos-12`

### PR DESCRIPTION
**Pull request by Milerius**
## Description

- upgrade to ubuntu 22.04 for last gcc/boost version
- fix trezorcrypto compilation
- add missing optional include
- upgrade to c++20 standalone, don't use any feature
- use TW:: for erase/erase_if algorithm, need to check if available on all platform before deleting the code.
- fixes #2359 

## How to test

run unit tests

## Types of changes

Upgrade C++ standard

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

### CODE REVIEW

**Comment by Milerius** [comment]
@catenocrypt @hewigovens It compiles on c++20 everywhere, but there is a llvm crash on command line regarding coverage:

```
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /usr/bin/llvm-cov-11 /usr/bin/llvm-cov-11 gcov /home/runner/work/wallet-core/wallet-core/build/CMakeFiles/TrustWalletCore.dir/src/Base64.cpp.gcda -b -x -i 
```

If someone have an idea please let me know

**Comment by hewigovens** [comment]
I guess we need to upgrade llvm-cov too

**Comment by Milerius** [comment]
> Looks good, can you update Dockerfile as well?

Should we keep `apt-add-repository -y ppa:mhier/libboost-latest` ? I think installing the libboost package comes with boost 1.74 on ubuntu 22.04

**Comment by hewigovens** [comment]
no need if we can install boost from official source, also thinking of managing boost by the script

**Comment by Milerius** [comment]
> no need if we can install boost from official source, also thinking of managing boost by the script

Sure, I need to fix that on another machine, somehow if I try to run this dockerfile on a mac os M1 it tries to use ubuntu arm version

**Comment by Milerius** [comment]
@hewigovens The reason the dockerfile fails now is that it need this pr as fixes for trezor-crypto.

**Comment by hewigovens** [comment]
I see, let's merge trezor fix for master first?

**Comment by Milerius** [comment]
> I see, let's merge trezor fix for master first?

done

**Review by hewigovens — APPROVED** [review]

**Review by xboehmx33 — APPROVED** [review]

**Review by xboehmx33 — APPROVED** [review]

**Review by xboehmx33 — APPROVED** [review]

**Review by xboehmx33 — APPROVED** [review]

**Review by xboehmx33 — APPROVED** [review]

**Comment by hewigovens** [comment]
@Milerius try to run `tools/android-build` `tools/ios-build` and `tools/ios-xcframework` to see if that works

**Comment by Milerius** [comment]
> @Milerius try to run `tools/android-build` `tools/ios-build` and `tools/ios-xcframework` to see if that works

All passed

**Comment by hewigovens** [comment]
This pr needs to rebase master, I see a few commits already in master

**Pull request merged**
