### PR TITLE
Signing tests for Binance Smart Chain

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Signing tests for Binance Smart Chain.  Test for native (BNB) transfer, and a token transfer.
Ethereum signing code is used.
Tests use testnet IDs.

## Testing instructions

All unit tests.

## Types of changes

* New test

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

**Comment by catenocrypt** [comment]
@hewig, please have a look if it makes sense to include this now or not.

**Comment by hewigovens** [comment]
bsc signing (Ethereum) should just work, what we need is cross chain contract encoder + bc cross chain / staking messages support

**Comment by catenocrypt** [comment]
> bsc signing (Ethereum) should just work, what we need is cross chain contract encoder + bc cross chain / staking messages support

Yes, this is just the first easy step :)

**Comment by catenocrypt** [comment]
> Let's move this into `Ethereum` folder? `TokenTransfer` demonstrates how to sign smart contract call tx

The point here is how to sign for binance chain, using ethereum code.  That's why I did not put in ethereum folder.

**Comment by hewigovens** [comment]
since smart chain is Ethereum, if people wants testnet or token transfer example, we can refer to these tests

**Comment by hewigovens** [comment]
I will move these tests to my working branch later, close this now

**Pull request closed without merging**
