### PR TITLE
Support MonetaryUnit (MUE)

### PR DESCRIPTION
**Pull request by sotblad**
## Description

MonetaryUnit coin integration.
https://monetaryunit.org
https://chainz.cryptoid.info/mue/

## Checklist

- [ ] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [ ] Update documentation as needed.

### CODE REVIEW

**Comment by hewigovens** [comment]
to fix codecov, please add address validation tests to `CoinTests.cpp`

**Comment by hewigovens** [comment]
Can you also add a tx signing test? like `TWZelcashTransactionTests.cpp`

**Comment by hewigovens** [comment]
here is a bitcoin fork check list, can you make sure these are all covered?

- [ ] derive bip44 p2pkh address or bip84 bech32 address
- [ ] validate bip44 / bip49 / bip84 addresses (p2pkh / p2sh prefix, hrp)
- [ ] check xpub / xprv version
- [ ] cross check xpub / xprv with ledger / trezor
- [ ] derive address from xpub (random index)
- [ ] check lock script for  bip44 / bip49 / bip84 addresses (can do it on block explorer)
- [ ] check tx detail url
- [ ] check fee preference, estimatefee/2 or static
- [ ] add signer test

**Comment by sotblad** [comment]
* [x]  derive bip44 p2pkh address or bip84 bech32 address
* [x]  validate bip44 / bip49 / bip84 addresses (p2pkh / p2sh prefix, hrp)
* [x]  check xpub / xprv version
* [x]  cross check xpub / xprv with ledger / trezor
* [x]  derive address from xpub (random index)
* [x]  check lock script for  bip44 / bip49 / bip84 addresses (can do it on block explorer)
* [x]  check tx detail url
* [x]  check fee preference, estimatefee/2 or static
* [x]  add signer test

**Pull request merged**
