### PR TITLE
Fix compile errors on Ubuntu

### PR DESCRIPTION
**Pull request by phuang**
## Description

Fix several compile errors on Ubuntu with clang-11

## Testing instructions

Build on Ubuntu

## Types of changes

Fix several compile errors on Ubuntu with clang-11

## Checklist

- [ ] Prefix PR title with `[WIP]` if necessary.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [ ] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

**Comment by hewigovens** [comment]
Linux CI is still configured with clang 10, I guess the changes will be compatible for both?

**Comment by phuang** [comment]
> Linux CI is still configured with clang 10, I guess the changes will be compatible for both?

I think so, since Linux CI / build (pull_request) is successful.

**Comment by phuang** [comment]
> Can you check this https://github.com/trustwallet/wallet-core/runs/3877564388 ? I removed clang 10 from CI, seems not working

Yeah. There is other build errors with clang11 for me too. I have other fixes in CMakefile.txt. However I am not sure they are safe. So I didn't include them in this merge request. 
Should we put them in a separate merge request?

**Comment by hewigovens** [comment]
thanks, will try too

**Pull request merged**
