### PR TITLE
[Cocoapods] Fix podspec lint issue and one Polkadot typo

### PR DESCRIPTION
**Pull request by hewigovens**
Changes:
1. trim " from download url
2. fix spec name (should be w/o `.podspec`)
3. fixes https://github.com/trustwallet/wallet-core/issues/1428 and add a test

### CODE REVIEW

**Review by vikmeup — APPROVED** [review]

**Comment by hewigovens** [comment]
don't merge it yet, will add a `bond_extra` test

**Comment by hewigovens** [comment]
added

**Review by vikmeup — APPROVED** [review]

**Comment by Godhunter97** [comment]
added

**Review by catenocrypt — APPROVED** [review]

**Comment by emadami3060** [comment]
در تاریخ دوشنبه ۱۰ مهٔ ۲۰۲۱،‏ ۲۳:۳۴ Adam R ***@***.***> نوشت:

**Pull request merged**
