### PR TITLE
Update googletest to 1.11 to fix build with gcc 11

### PR DESCRIPTION
**Pull request by PiRK**
## Description
Recent versions of gcc (11.x) changed some rule about uninitialized variables, causing a warning which is for some reason considered as an error when I try to run `bootstrap.sh`. See https://github.com/google/googletest/issues/3219 and https://github.com/google/googletest/pull/3024

This fixes it by updating googletest to 1.11.00

## Testing instructions
On Ubuntu 21.10, follow the build instructions, then try to run `bootstrap.sh`.

Without the patch, it causes the following error:
```
$ ./bootstrap.sh
#### Initializing... ####
PREFIX: /home/pierre/dev/wallet-core/build/local
patching cmake minimum version
patching file CMakeLists.txt
patching file googletest/CMakeLists.txt
patching file googlemock/CMakeLists.txt
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "3.9.7")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pierre/dev/wallet-core/build/local/src/gtest/googletest-release-1.10.0
Scanning dependencies of target gtest
[ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /home/pierre/dev/wallet-core/build/local/src/gtest/googletest-release-1.10.0/googletest/src/gtest-all.cc:42:
/home/pierre/dev/wallet-core/build/local/src/gtest/googletest-release-1.10.0/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
/home/pierre/dev/wallet-core/build/local/src/gtest/googletest-release-1.10.0/googletest/src/gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
 1301 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/pierre/dev/wallet-core/build/local/src/gtest/googletest-release-1.10.0/googletest/src/gtest-death-test.cc:1290:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
 1290 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
/home/pierre/dev/wallet-core/build/local/src/gtest/googletest-release-1.10.0/googletest/src/gtest-death-test.cc:1299:7: note: ‘dummy’ declared here
 1299 |   int dummy;
      |       ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [googletest/CMakeFiles/gtest.dir/build.make:82: googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: googletest/CMakeFiles/gtest.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist
None of the checklist items are applicable.

### CODE REVIEW

**Comment by hewigovens** [comment]
@PiRK could you please check if gtest 1.11.0 has fixed this or not? also `sed` on macOS by default is bsd version, that's why iOS CI failed

**Comment by PiRK** [comment]
> @PiRK could you please check if gtest 1.11.0 has fixed this or not? also `sed` on macOS by default is bsd version, that's why iOS CI failed

I believe gtest 1.11 has fixed this. I can compile it without an error. I initially assumed that it wasn't fixed in 1.11 because when I searched for the error message I saw reports of the same error happening with that version, but those users must have been mistaken, or maybe they were building the master branch.

I will update the PR to simply use 1.11 instead of 1.10, rather than patching an old version, if that is OK with you.

**Comment by hewigovens** [comment]
Yes, let's try 1.11.0

**Comment by PiRK** [comment]
Note that I removed the patches becauses all the relevant `cmake_minimum_required` versions have been updated to 2.8.12:

https://github.com/google/googletest/blob/release-1.11.0/CMakeLists.txt#L4
https://github.com/google/googletest/blob/release-1.11.0/googlemock/CMakeLists.txt#L45
https://github.com/google/googletest/blob/release-1.11.0/googletest/CMakeLists.txt#L56

**Review by hewigovens — APPROVED** [review]
Thanks for the update

**Review by vikmeup — APPROVED** [review]

**Pull request merged**
