### PR TITLE
Enable bitcode for iOS releases

### PR DESCRIPTION
**Pull request by hewigovens**
iOS release size form 15mb -> 136mb

### CODE REVIEW

**Comment by vikmeup** [comment]
Can we not use it for now? If size of the app increases so much

**Comment by hewigovens** [comment]
this is just download size, the final archived framework size is around 72 mb

**Comment by vikmeup** [comment]
Does the app stays the same size? When being released

**Comment by hewigovens** [comment]
a little bigger, archived WalletCore framework in archive folder is 72.4 mb vs 42.9 mb, old wallet core .a files don't have bitcode

**Comment by hewigovens** [comment]
we could remove macos slice, 25% off, but still 200mb

**Review by vikmeup — APPROVED** [review]

**Review by catenocrypt — APPROVED** [review]

**Pull request merged**
