### PR TITLE
Adding UltraPro blockchain in trust wallet

### PR DESCRIPTION
**Pull request by UltraProDeveloper**
Added ultrapro blockchain json

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by rkokhatskyi — CHANGES_REQUESTED** [review]
Please do not commit VS related files, feel free to adjust .gitignore to exclude .vs directory

**Comment by UltraProDeveloper** [comment]
@rkokhatskyi Excluded vs directory. Is there any changes required?

**Comment by rkokhatskyi** [comment]
> @rkokhatskyi Excluded vs directory. Is there any changes required?

Hi @UltraProDeveloper, I see there's one more [file](https://github.com/UltraProDeveloper/wallet-core/blob/master/.vs/wallet-core/v17/.wsuo) committed `.vs/wallet-core/v17/.wsuo` from the `.vs` directory

**Comment by UltraProDeveloper** [comment]
@rkokhatskyi did that also. is there anything needed?

**Comment by satoshiotomakan** [comment]
Hi @UltraProDeveloper, thank you for the contribution! We will review the PullRequest early next year.

**Comment by UltraProDeveloper** [comment]
@satoshiotomakan  @angelol  @rkokhatskyi  Happy new year everyone.
In the new year , we have new resolutions & we will happy to to registered on trustwallet as by default blockchain. so kindly review our PR request as soon as possible.

**Comment by Milerius** [comment]
Hello this chain is not planned to be added in trustwallet for now.

**Comment by MrSahilShaikh** [comment]
@Milerius Can I know reason behind it?
Is there any charges then we are ready to pay it?

**Pull request closed without merging**
