### PR TITLE
[Staking]: add NEAR staking

### PR DESCRIPTION
**Pull request by miloserdow**
## Description

Add tests for NEAR staking, as a part of #2674.

## How to test

Run the new test manually.

## Todo:

- [X] Stake
- [X] Unstake
- [X] Claim rewards - part of unstake tx

### CODE REVIEW

**Comment by miloserdow** [comment]
## Byte by byte comparison with the official NEAR wallet

### NEAR web wallet transaction
sender addr sz: **40**
sender addr: **00000062386435646632353034373834313336353030386633306662366233306464383230653961383464383639663035363233643131346539363833316632666266**(b8d5df25047841365008f30fb6b30dd820e9a84d869f05623d114e96831f2fbf)
pubkey: [type] **00** [key] **ce0093e8d2bbea76f5981ee94e879f8241941df51ee412afbebde05bf9eaf8c8**
nonce **04baed4cab460000**
receiver sz: **11**
receiver: **000000617661646f2e706f6f6c76312e6e656172**
blockhash: **e78680996127b7a0f3f2343502e442f24366cba5f79cb72f8bc6d0debb26ce24**
number of actions: **01**
action type: **00000002** - Contract call
method name: **110000006465706f7369745f616e645f7374616b65 000000 7b7d** ("deposit_and_stake" + 0x000000 + "{}")
arg count: **00**
gas: **d098d4af71000000**
deposit: **0080f64ae1c7022d15000000000000**

separator **00**
signature: **2cdae8aebf2a4cbeaed679712e9b8f6b8e6715d6268d4f7a8bb0a624fd3c9951d5cc751ac3f6c6377d19deede8d45da8db279f08136a3bd3a09fd7ccdb93460a**


### WC transaction
sender addr sz: **40** 
sender addr: **00000062386435646632353034373834313336353030386633306662366233306464383230653961383464383639663035363233643131346539363833316632666266**
pubkey: [type] **00** [key] **ce0093e8d2bbea76f5981ee94e879f8241941df51ee412afbebde05bf9eaf8c8**
nonce: **04baed4cab460000**
receiver sz: **11**
receiver: **000000617661646f2e706f6f6c76312e6e656172**
blockhash: **e78680996127b7a0f3f2343502e442f24366cba5f79cb72f8bc6d0debb26ce24**
number of actions: **01**
action type: **00000002** - Contract call
method name: **110000006465706f7369745f616e645f7374616b65 00000000** ("deposit_and_stake" + 0x00000000)
arg count: **00**
gas: **d098d4af71000000**
deposit: **80f64ae1c7022d15000000000000**

separator: **00**
signature: **85bf2ac23c243ef36c450259dfb6ef28d0199e2715256a4aabf9c1e21f49019684f16b4fa2b718680fe232db1854014b3c3c4065d835c0728c0b7eca4ccaa807**


## Conclusion
There is a difference in how function call is serialised. NEAR RPC nodes won't accept it our way.

**Comment by miloserdow** [comment]
RPC gives the following error:

>...
>"message": "Parse error",
>"data": "Failed to decode transaction: unknown key type '133'"
> ...

**Comment by Dstoney** [comment]
How long

**Comment by hewigovens** [comment]
Did you figure out which step was wrong? only function call I guess?

**Comment by Milerius** [comment]
Before undrafting:

- Add url from the transaction at the top of the unit test
- Add unit test for unstaking
- Add unit test for claiming rewards

**Comment by miloserdow** [comment]
Claiming rewards happens automatically in unstaking test case.

**Review by Milerius — APPROVED** [review]

**Review by hewigovens — APPROVED** [review]

**Pull request merged**
