### PR TITLE
[WIP] Android CI build speedup

### LINKED ISSUE #975: [CI] Improve Android CI speed
ndk supports ccache, the trick is when to update ccache folder, probably we can check `cache hit rate` (lower than 50%)

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Android build: limit debug build to x86 abi, to speed up build.
Fixes #975 .
CI time reduced from over 30 minutes to about 16.

## Testing instructions

./tools/android-test

## Types of changes

* Process change (non-breaking, testing process)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

**Comment by catenocrypt** [comment]
@madcake , @vcoolish : I've managed to reduce the Android CI time from above 30 minutes to about 16, by limiting debug build to 'x86' abi only.  Do you see any drawback/problem with this?
https://github.com/trustwallet/wallet-core/pull/1072/files

It would be better to have x86_64 instead of 32-bit x86, but I could not get the emulator to work with it.  Can it be done?

Any other idea for speedup?

**Comment by catenocrypt** [comment]
> It won't change release build, correct?

Release build is not affected.

**Comment by madcake** [comment]
> > It won't change release build, correct?
> 
> 
> 
> Release build is not affected.

I understand. We should run tests for all abi!

**Comment by vikmeup** [comment]
> > > It won't change release build, correct?
> > 
> > 
> > Release build is not affected.
> 
> I understand. We should run tests for all abi!

+1

**Comment by hewigovens** [comment]
@madcake iOS is only tested on simulators

**Comment by catenocrypt** [comment]
- Android CI is the longest, often over 30 minutes
- proposed way to reduce it is to limit debug build to x86 arch only
- tests were run on x86 emulator only
- it would be good to build on all 4 abi platforms, in parallel builds, but I don't see how is this possible (testing command builds full debug)
- separate GH action to build relase with all 4 abis could be added, but that would also last 40-45 mins
- it would be good to test on all 4 abi platforms, but this was not done before, and I don't see how is this possible with emulator.

I still propose to reduce the scope of debug building to x86 abi, keep testing scope x86 abi, in order to speedup android CI, which is a gated check for merges.

**Review by madcake — APPROVED** [review]

**Pull request merged**
