### PR TITLE
Add an option to remove selected accounts from wallet

### PR DESCRIPTION
**Pull request by dstranz**
## Description

Add an option to remove selected accounts from wallet via swift KeyStore.

## Testing instructions

Run testRemoveAccounts test.

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.

### CODE REVIEW

**Comment by leoneparise** [comment]
The implementation should be on C++ side and cover all platforms.

**Comment by dstranz** [comment]
@leoneparise It would be better to rewrite them one day, but renameWallet and updatePassword methods are also implemented in swift Keystore.

**Comment by dstranz** [comment]
@leoneparise OK, I moved that to C++ :)

**Comment by hewigovens** [comment]
@dstranz could you please fix codecov / codacy ? Thanks

**Pull request merged**
