### PR TITLE
Update and fix copyright year 2020

### PR DESCRIPTION
**Pull request by hewigovens**

### CODE REVIEW

**Comment by hewigovens** [comment]
Just replace all in vscode

**Comment by catenocrypt** [comment]
Have to watch out pending PRs; hopefully it will not cause merge issues; but some files may be left out (new files from pending PRs).

**Comment by vikmeup** [comment]
Maybe just: `Copyright (c) Trust Wallet` or `Copyright (c) DApps Platform Inc.`

**Comment by catenocrypt** [comment]
> Is theres away not to modify this every year?

I think the year has to be there, legal sillyness.  But updating is not a must, not modified files can stay with older year.

**Comment by vikmeup** [comment]
Let's not update this then? Keep it as is is fine

**Pull request merged**
