### PR TITLE
[WIP] Protobuf version change to 3.11.

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Protobuf version change from 3.7.0 to 3.10.1.  Fixes issue #721 .

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Build is OK for now, but there are still undefined reference linker errors.

**Comment by hewigovens** [comment]
hmm, is there any breaking change? why linking failed

**Comment by catenocrypt** [comment]
It looks like all symbols are missing, so it must be some cmake/linkerflag issue, I'm still struggling with it.

**Comment by catenocrypt** [comment]
Hmm, it looks like both tools/install-dependencies and our make has built protobuf, in different locations, and they got mixed up.  Now I am thinking to remove protobuf building from our CMake files, it is enough if it is built by tools/install-dependencies .

**Comment by catenocrypt** [comment]
We have a bit of a circular dependency problem:
- to verify new version in PR CI build, we need an updated Docker image, as CI build uses protobuf as prepared in the docker image
- to create a new docker image, we need the changes to be committed to master branch, as Dockerfile takes it from there.

Note: docker image on hub:   https://hub.docker.com/r/trustwallet/wallet-core

**Comment by hewigovens** [comment]
`TrustWalletCore.podspec` in root folder also needs to be updated

**Pull request closed without merging**
