### PR TITLE
feat: macos swift package

### PR DESCRIPTION
**Pull request by grachyov**
add macos to spm https://github.com/trustwallet/wallet-core/issues/3513
@satoshiotomakan could you please include macos in a swift package releases?

### CODE REVIEW

**Comment by grachyov** [comment]
Screenshot 2023-11-03 at 17 39 37

**Comment by grachyov** [comment]
@Milerius is there anything else that needs to be changed to make next SPM releases available for macOS?

**Comment by grachyov** [comment]
@Milerius @satoshiotomakan could you please help with this one?

**Comment by hewigovens** [comment]
Hey,the team might not have bandwidth to build and test for macOS Package, have you built, tested and verified?

**Comment by grachyov** [comment]
@hewigovens hey, thanks for the response!

i did not test it – and i have switched back to cocoapods – do not need spm anymore.

unrelated: can i dm you on x? https://x.com/ivangrachyov

**Comment by hewigovens** [comment]
Sure, I followed you back, let's close this issue

**Pull request closed without merging**
