### PR TITLE
[Solana] Refine `programId` and `accounts` comments, `CreditOnly` -> `ReadOnly`

### PR DESCRIPTION
**Pull request by CriesofCarrots**
## Description

Fixes a couple nits I noticed when looking at #2935
No functional changes

## How to test
Noop

## Types of changes

- Code comments: correct Instruction field descriptions
- Rename: update MessageHeader field names to match definitions https://github.com/solana-labs/solana/blob/f91e63dfe9527199acb692a43629a97f0bf78e1f/sdk/program/src/message/mod.rs#L96
 

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by hewigovens — DISMISSED** [review]
🚀

**Comment by Milerius** [comment]
As I've refactored the code in #2935 - it may need a rebase afterwards.

**Comment by CriesofCarrots** [comment]
> As I've refactored the code in #2935 - it may need a rebase afterwards.

Np, I can rebase if that lands first.

**Comment by Chukwulawrence** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by CriesofCarrots** [comment]
I assume that last comment is phishing. We've had good luck on our repo reporting similar stuff to github.

**Comment by Milerius** [comment]
> I assume that last comment is phishing. We've had good luck on our repo reporting similar stuff to github.

Yes, we always report, but they always came back 😂

**Comment by Milerius** [comment]
I just merged the initial pull request @CriesofCarrots jfyi

**Review by Milerius — APPROVED** [review]

**Review by hewigovens — APPROVED** [review]

**Pull request merged**
