### PR TITLE
Add getKeyByCurve method

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Add new method for get private key by curve type
This PR is a slight rework of original #2350 .

## How to test

HDWallet/Key unit tests.

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by hewigovens — APPROVED** [review]
Is this one finished?

**Review by Milerius — APPROVED** [review]

**Comment by berniceburgo** [comment]
Access

**Comment by berniceburgo** [comment]
Access

**Comment by trastvolt** [comment]
ar/getkeybycurve

**Comment by trastvolt** [comment]
ar/getkeybycurve

**Pull request merged**
