### PR TITLE
Aff

### PR DESCRIPTION
**Pull request by affiliatedkat**
## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

**Comment by affiliatedkat** [comment]
R

**Review by affiliatedkat — COMMENTED** [review]
Help

**Comment by catenocrypt** [comment]
Please be more specific what you are trying to accomplish; what problem are you trying to solve.

**Comment by affiliatedkat** [comment]
Hello can you help me interact with my trust wallet and a smart
contract.... I don't understand anything when it comes to this... but I
stake value in the governance vault on Value Defi protocol, I have a bunch
of profit and I have no idea how to get anything to my account. Or how
anything works at all, I'm a newbie who knows nothing about it.

**Comment by affiliatedkat** [comment]
On Valuedefi.io I stake value in the governance vault. By doing so you earn rewards and your profit is auto compounded into the protocol. I'm trying to interact with the smart contract and get my rewards. Or atleast find out where they are going and how much I  have..... I'm a dummy when it comes to this stuff.... sorry thats why I was just messing around with guthub trying to see what I could learn and figure out..... if you can't help I understand but I decided to just ask because I might have asked the right person

**Comment by catenocrypt** [comment]
If you need _development_ support for Trust Wallet, I recommend using our Telegram channel
https://t.me/trust_developers

**Pull request closed without merging**
