### PR TITLE
[Fix] Even more fixes of namespace collisions in unity build

### PR DESCRIPTION
**Pull request by miloserdow**
## Description

As we're now using unity build, all the translation units are being merged into one causing name conflicts. To avoid collisions, we need to get rid of using namespace TW directive and specify namespaces carefully instead.

## How to test

Run unity build and unit tests.

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [X] If there is a related Issue, mention it in the description.
- [x] Fix extra qualifier warnings
- [x] Change codegen not to generate "using namespace"

### CODE REVIEW

**Comment by miloserdow** [comment]
Apologies for the style changes in this PR, it's just clang-tidy doing its job.

**Comment by Ashleyburgos** [comment]
Access

**Comment by Milerius** [comment]
Will approve after CI passed, it's seems that some code still need to be updated!

**Comment by hewigovens** [comment]
We have some templates too, can you also update them? `codegen/lib/templates/newcoin`

**Comment by miloserdow** [comment]
Now having some linking problems for tests. Probably because I put tests in a separate namespace (e.g. TW::Aeternity::tests not TW::Aeternity)

**Comment by miloserdow** [comment]
Work left:

- [ ] Fix extra qualifier warnings
- [ ] Change codegen not to generate "using namespace"

**Comment by Ashleyburgos** [comment]
Approved

**Review by hewigovens — DISMISSED** [review]
This is hard work 🚀, take hours to review it

**Comment by Ashleyburgos** [comment]
Approved

**Review by Milerius — DISMISSED** [review]

**Review by catenocrypt — APPROVED** [review]

**Review by hewigovens — APPROVED** [review]
`ValueEncoderTests` has some  shadowing warnings

**Review by Milerius — APPROVED** [review]

**Review by catenocrypt — APPROVED** [review]

**Pull request merged**
