### PR TITLE
New ‘newevmchain’ script, subset of ‘newcoin’

### LINKED ISSUE #2791: Specialized newevmchain script to simplify New EVM chain addition
In the New EVM chain case, documented here:

https://developer.trustwallet.com/wallet-core/newblockchain/newevmchain

we use the `newcoin` script, that makes about 10 changes/additions, of which only 2 re needed, the rest need to be discarded. We could have a customized script that makes only those required changed.

Description should be updated (simplified).

There is also an outdated path:
`tests/CoinAddressDerivationTests.cpp` -> `tests/common/CoinAddressDerivationTests.cpp`

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Added new `newevmchain` script, a subset of `newcoin`, to be used in the EVM chain case. It skips some changes/additions that are not needed in this use case.
Fixes #2791.

## How to test

Add a new Etehreum chain to `registry.json`, invoke `codegen/bin/newevmchain <id>`, observe changed/added files.

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by Milerius — DISMISSED** [review]
Not sure if we really need that with the new custom network feature, the goal is to not add Evm and cosmos chains through wallet core in the future.

**Comment by SUPPORTTEAMHERR** [comment]
> ## Description
> 
> Added new `newevmchain` script, a subset of `newcoin`, to be used in the EVM chain case. It skips some changes/additions that are not needed in this use case.
> Fixes #2791.
> 
> ## How to test
> 
> Add a new Etehreum chain to `registry.json`, invoke `codegen/bin/newevmchain <id>`, observe changed/added files.
> 
> ## Types of changes
> 
> 
> 
> 
> 
> * New feature (non-breaking change which adds functionality)
> 
> 
> 
> ## Checklist
> 
> 
> 
> - [x] Create pull request as draft initially, unless its complete.
> - [x] Add tests to cover changes as needed.
> - [x] Update documentation as needed.
> - [x] If there is a related Issue, mention it in the description.
> 
> If you're adding a new blockchain
> 
> - [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Review by hewigovens — COMMENTED** [review]
I suggest adding a `evm` parameter to this, not duplicate and comment out not used lines

**Comment by catenocrypt** [comment]
Refactored to minimize code duplication.
Moved `newcoin` to lib, and although I did rename in a separate commit, diff shows it as a new plus old file...

**Review by hewigovens — APPROVED** [review]

**Review by Milerius — APPROVED** [review]

**Pull request merged**
