### PR TITLE
[iOS] Add static linking pod example

### PR DESCRIPTION
**Pull request by hewigovens**
prepare for #1159

### CODE REVIEW

**Review by catenocrypt — APPROVED** [review]

**Comment by vikmeup** [comment]
What's the purpose to have two separate pod specs? I find it hard to support both. What are the benefits of this?

**Comment by hewigovens** [comment]
This one is only for development, easier to test compiling from source code, there is one step `s.prepare_command = 'tools/install-dependencies && tools/generate-files'` in `TrustWalletCore.podspec` which takes ages to install 

there is another `probject.yml` and binary podspec in `ios-release`

I can try to simplify protobuf files later

**Comment by vikmeup** [comment]
can we rename file to `WalletCore-development.podspec`? so we know it's only used for development purpose and not for production use.

**Comment by hewigovens** [comment]
good suggestion, will do

**Review by vikmeup — COMMENTED** [review]
What's the status on this?

**Comment by hewigovens** [comment]
I will merge this one into pr #1269

**Pull request closed without merging**
