### PR TITLE
[WIP] Support building for Windows under Visual Studio

### PR DESCRIPTION
**Pull request by kaetemi**
## Description

Work in progress, rough draft. Changes to build under Visual Studio. Builds. Not fully tested.

### Requirements
* Visual Studio 2022
* CMake
* Ruby

### Build

```
powershell .\tools\windows-dependencies.ps1
powershell .\tools\windows-generate.ps1
powershell .\tools\windows-build.ps1
powershell .\tools\windows-samples.ps1
powershell .\tools\windows-tests.ps1
```

### CODE REVIEW

**Comment by kaetemi** [comment]
TrezorCrypt tests all pass.

Wallet Core has 5 failed tests.

```
[----------] Global test environment tear-down
[==========] 1462 tests from 313 test suites ran. (31256 ms total)
[  PASSED  ] 1457 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] FIOEncryption.getSharedSecret
[  FAILED  ] FIOEncryption.encryptAndEncode
[  FAILED  ] FIOEncryption.encryptEncodeDecodeDecrypt
[  FAILED  ] FIOTransactionBuilder.NewFundsRequest
[  FAILED  ] TWStoredKey.storeAndImportJSON

 5 FAILED TESTS
```

```
[ RUN      ] FIOEncryption.getSharedSecret
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(120): error: Expected equality of these values:
  hex(secret)
    Which is: "9314a4ff9066cda49e770237ca4bd1b57b129ab7bdd7fe2b717a19a4f21f00a2a873163cfc6a39935c8ce5c1a18f8b0b65cab95d981f3b0620be2195650caa6b"
  "a71b4ec5a9577926a1d2aa1d9d99327fd3b68f6a1ea597200a0d890bd3331df300a2d49fec0b2b3e6969ce9263c5d6cf47c191c1ef149373ecc9f0d98116b598"
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(127): error: Expected equality of these values:
  hex(secret)
    Which is: "c0f430ad78b4aac9c02e8721cd371c11f106dd4376eee3ccd1b6504d5ae1e56006f6fb1ec78e94ceec430adbb52594218aa1b22f61d1d74350c3af02872c8116"
  "a71b4ec5a9577926a1d2aa1d9d99327fd3b68f6a1ea597200a0d890bd3331df300a2d49fec0b2b3e6969ce9263c5d6cf47c191c1ef149373ecc9f0d98116b598"
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(134): error: Expected equality of these values:
  hex(secret)
    Which is: "e8fb3202a3c6d88cb6bc06b787e03d97ae8033ed0781b67f6c60739da0e0fbac60da9d7b2c4861586074fcb5009d39070a5b9825f288cc424c9f74b90a660ea3"
  "3f0840df1912e24d85f39008a56550c31403e096fce7fa9d7886fab8e5c2ceb66b4139c8f4f4172fd9f455e76c2e8913a3d734f51a1951090ce9ec660671957d"
[  FAILED  ] FIOEncryption.getSharedSecret (8 ms)
[ RUN      ] FIOEncryption.encryptAndEncode
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(146): error: Expected equality of these values:
  hex(encrypted)
    Which is: "f300888ca4f512cebdc0020ff0f7224c6eb4dfa7c1cc04df248cb68b03e485b0ff488ba0d4506dd1b420162c8aa3d5dabc83853654335f5acd7c6aa72701f2e70cd2706973a206351f2b48de2a8057e7"
  "f300888ca4f512cebdc0020ff0f7224c0db2984c4ad9afb12629f01a8c6a76328bbde17405655dc4e3cb30dad272996fb1dea8e662e640be193e25d41147a904c571b664a7381ab41ef062448ac1e205"
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(148): error: Expected equality of these values:
  encoded
    Which is: "8wCIjKT1Es69wAIP8PciTG6036fBzATfJIy2iwPkhbD/SIug1FBt0bQgFiyKo9XavIOFNlQzX1rNfGqnJwHy5wzScGlzogY1HytI3iqAV+c="
  "8wCIjKT1Es69wAIP8PciTA2ymExK2a+xJinwGoxqdjKLveF0BWVdxOPLMNrScplvsd6o5mLmQL4ZPiXUEUepBMVxtmSnOBq0HvBiRIrB4gU="
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(156): error: Expected equality of these values:
  hex(encrypted)
    Which is: "f300888ca4f512cebdc0020ff0f7224cc0bcc26cfc6028953dfa68c22cb183bfdd8e40e57c479094039a01ea2cc7c734e88d3a0ce29e7b5ccf19c172779f1552f4da7451d45d214434ef6b45fb588659"
  "f300888ca4f512cebdc0020ff0f7224c0db2984c4ad9afb12629f01a8c6a76328bbde17405655dc4e3cb30dad272996fb1dea8e662e640be193e25d41147a904c571b664a7381ab41ef062448ac1e205"
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(158): error: Expected equality of these values:
  encoded
    Which is: "8wCIjKT1Es69wAIP8PciTMC8wmz8YCiVPfpowiyxg7/djkDlfEeQlAOaAeosx8c06I06DOKee1zPGcFyd58VUvTadFHUXSFENO9rRftYhlk="
  "8wCIjKT1Es69wAIP8PciTA2ymExK2a+xJinwGoxqdjKLveF0BWVdxOPLMNrScplvsd6o5mLmQL4ZPiXUEUepBMVxtmSnOBq0HvBiRIrB4gU="
[  FAILED  ] FIOEncryption.encryptAndEncode (4 ms)
[ RUN      ] FIOEncryption.encryptEncodeDecodeDecrypt
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(175): error: Expected equality of these values:
  hex(encrypted)
    Which is: "f300888ca4f512cebdc0020ff0f7224c1ba08cea4708d7127ae10a8be864726e543d51e8a48af75f91d9b50fce9b9bf073c8e14c8e33f51b0b108cd3818b63d5721a879fa6f83d5ab5a1ccfa179c62ae"
  "f300888ca4f512cebdc0020ff0f7224c0db2984c4ad9afb12629f01a8c6a76328bbde17405655dc4e3cb30dad272996fb1dea8e662e640be193e25d41147a904c571b664a7381ab41ef062448ac1e205"
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(177): error: Expected equality of these values:
  encoded
    Which is: "8wCIjKT1Es69wAIP8PciTBugjOpHCNcSeuEKi+hkcm5UPVHopIr3X5HZtQ/Om5vwc8jhTI4z9RsLEIzTgYtj1XIah5+m+D1ataHM+hecYq4="
  "8wCIjKT1Es69wAIP8PciTA2ymExK2a+xJinwGoxqdjKLveF0BWVdxOPLMNrScplvsd6o5mLmQL4ZPiXUEUepBMVxtmSnOBq0HvBiRIrB4gU="
X:\source_other\wallet-core\tests\FIO\EncryptionTests.cpp(180): error: Expected equality of these values:
  hex(decoded)
    Which is: "f300888ca4f512cebdc0020ff0f7224c1ba08cea4708d7127ae10a8be864726e543d51e8a48af75f91d9b50fce9b9bf073c8e14c8e33f51b0b108cd3818b63d5721a879fa6f83d5ab5a1ccfa179c62ae"
  "f300888ca4f512cebdc0020ff0f7224c0db2984c4ad9afb12629f01a8c6a76328bbde17405655dc4e3cb30dad272996fb1dea8e662e640be193e25d41147a904c571b664a7381ab41ef062448ac1e205"
unknown file: error: C++ exception with description "Decrypt failed, HMAC mismatch" thrown in the test body.
[  FAILED  ] FIOEncryption.encryptEncodeDecodeDecrypt (6 ms)
```

```
[ RUN      ] FIOTransactionBuilder.NewFundsRequest
X:\source_other\wallet-core\tests\FIO\TransactionBuilderTests.cpp(101): error: Expected equality of these values:
  R"({"compression":"none","packed_context_free_data":"","packed_trx":"17b9625e344801e94ddd000000000100403ed4aa0ba85b00acba384dbdb89a01702096fedf5bf9f900000000a8ed3232d2010e7461674066696f746573746e657412646170697862704066696f746573746e6574980141414543417751464267634943516f4c4441304f447a684533513779504a4738592f52486a69545576436163734a444a516243612f41643763354e36354f56366d3441566974596379654e7a4749306d4c366b5a71567348737837537845623471724d346435567258364939746a6842447067566b3078596575325861676759516b323168684972306c76412b7535546977545661673d3d0008af2f000000000c7a62777072727a796d736b620000","signatures":["SIG_K1_K95jnXSBCf1BnQXQPZzxKYPGxugwpbeVp2NSjN1kmYd9SQibvnSfh2ggmSVXii4Jvq3dtRHFA8s7n3kcQdLhY4KMrkgDgp"]})"
    Which is: "{\"compression\":\"none\",\"packed_context_free_data\":\"\",\"packed_trx\":\"17b9625e344801e94ddd000000000100403ed4aa0ba85b00acba384dbdb89a01702096fedf5bf9f900000000a8ed3232d2010e7461674066696f746573746e657412646170697862704066696f746573746e6574980141414543417751464267634943516f4c4441304f447a684533513779504a4738592f52486a69545576436163734a444a516243612f41643763354e36354f56366d3441566974596379654e7a4749306d4c366b5a71567348737837537845623471724d346435567258364939746a6842447067566b3078596575325861676759516b323168684972306c76412b7535546977545661673d3d0008af2f000000000c7a62777072727a796d736b620000\",\"signatures\":[\"SIG_K1_K95jnXSBCf1BnQXQPZzxKYPGxugwpbeVp2NSjN1kmYd9SQibvnSfh2ggmSVXii4Jvq3dtRHFA8s7n3kcQdLhY4KMrkgDgp\"]}"
  t
    Which is: "{\"compression\":\"none\",\"packed_context_free_data\":\"\",\"packed_trx\":\"17b9625e344801e94ddd000000000100403ed4aa0ba85b00acba384dbdb89a01702096fedf5bf9f900000000a8ed3232d2010e7461674066696f746573746e657412646170697862704066696f746573746e6574980141414543417751464267634943516f4c4441304f443578687567676c5676553037425142716e792f42325a71633343546d6d557168556d696c41425777433950524761394d58514c4e45327a72517a4a36552b42646e586474637a374a5555744a72503068505450574144497747362f6a71626e7365304a582b553159746b78762f654b4b4e7a4d76324f617a784c67392f364357513d3d0008af2f000000000c7a62777072727a796d736b620000\",\"signatures\":[\"SIG_K1_Jw3Tm9jCDhSBixAkX9B8C3raVyDKRWffpzLXW8rLHYookWyew4Rfw5UGzc89ZTV4DsaPxBEgyvT8jnWAhju2FVr8rVxP9N\"]}"
X:\source_other\wallet-core\tests\FIO\TransactionBuilderTests.cpp(113): error: Expected equality of these values:
  R"({"compression":"none","packed_context_free_data":"","packed_trx":"289b295ec99b904215ff000000000100403ed4aa0ba85b00acba384dbdb89a01102b2f46fca756b200000000a8ed32328802106d6172696f4066696f746573746e657410616c6963654066696f746573746e6574c00141414543417751464267634943516f4c4441304f442f3575342f6b436b7042554c4a44682f546951334d31534f4e4938426668496c4e54766d39354249586d54396f616f7a55632f6c6c3942726e57426563464e767a76766f6d3751577a517250717241645035683433305732716b52355266416555446a704f514732364c347a6936767241553052764855474e382b685779736a6971506b2b7a455a444952534678426268796c69686d59334f4752342f5a46466358484967343241327834005ed0b2000000000c716466656a7a32613577706c0e726577617264734077616c6c657400","signatures":["SIG_K1_Kk79iVcQMpqpVgZwGTmC1rxgCTLy5BDFtHd8FvjRNm2FqNHR9dpeUmPTNqBKGMNG3BsPy4c5u26TuEDpS87SnyMpF43cZk"]})"
    Which is: "{\"compression\":\"none\",\"packed_context_free_data\":\"\",\"packed_trx\":\"289b295ec99b904215ff000000000100403ed4aa0ba85b00acba384dbdb89a01102b2f46fca756b200000000a8ed32328802106d6172696f4066696f746573746e657410616c6963654066696f746573746e6574c00141414543417751464267634943516f4c4441304f442f3575342f6b436b7042554c4a44682f546951334d31534f4e4938426668496c4e54766d39354249586d54396f616f7a55632f6c6c3942726e57426563464e767a76766f6d3751577a517250717241645035683433305732716b52355266416555446a704f514732364c347a6936767241553052764855474e382b685779736a6971506b2b7a455a444952534678426268796c69686d59334f4752342f5a46466358484967343241327834005ed0b2000000000c716466656a7a32613577706c0e726577617264734077616c6c657400\",\"signatures\":[\"SIG_K1_Kk79iVcQMpqpVgZwGTmC1rxgCTLy5BDFtHd8FvjRNm2FqNHR9dpeUmPTNqBKGMNG3BsPy4c5u26TuEDpS87SnyMpF43cZk\"]}"
  t
    Which is: "{\"compression\":\"none\",\"packed_context_free_data\":\"\",\"packed_trx\":\"289b295ec99b904215ff000000000100403ed4aa0ba85b00acba384dbdb89a01102b2f46fca756b200000000a8ed32328802106d6172696f4066696f746573746e657410616c6963654066696f746573746e6574c00141414543417751464267634943516f4c4441304f44794d4c5036414d777164726d79367434686163496233467467385543644f427a6337794f366f707647774c395573572f7a6c522b446f37507956444b477a5265474c564c70487138666a62514a522b72752b5168366e356363306d694734707249754e4341486a4341694b416c666936344c7777557843462f7854694c316b72626e6431582f715145742b727a39355175574c4f364b5031435679676f6649594e54302f7957764f39714c005ed0b2000000000c716466656a7a32613577706c0e726577617264734077616c6c657400\",\"signatures\":[\"SIG_K1_KaWnQTvhFyTeHyaJcuhbH1ghfRxNSDpgGutd2jikveqiD4ntTRMUmyRseBhpFybyozQPjPVHbcJZCVptym9KTobkzMbBjg\"]}"
[  FAILED  ] FIOTransactionBuilder.NewFundsRequest (5 ms)
```

```
[ RUN      ] TWStoredKey.storeAndImportJSON
X:\source_other\wallet-core\tests\interface\TWStoredKeyTests.cpp(153): error: Value of: length > 20
  Actual: false
Expected: true
unknown file: error: C++ exception with description "vector too long" thrown in the test body.
[  FAILED  ] TWStoredKey.storeAndImportJSON (88 ms)
```

**Comment by kaetemi** [comment]
All tests pass in Debug mode.

```
[----------] Global test environment tear-down
[==========] 1462 tests from 313 test suites ran. (53691 ms total)
[  PASSED  ] 1462 tests.
```

4 tests fail in Release mode.

```
[----------] Global test environment tear-down
[==========] 1462 tests from 313 test suites ran. (12119 ms total)
[  PASSED  ] 1458 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] FIOEncryption.getSharedSecret
[  FAILED  ] FIOEncryption.encryptAndEncode
[  FAILED  ] FIOEncryption.encryptEncodeDecodeDecrypt
[  FAILED  ] FIOTransactionBuilder.NewFundsRequest
```

**Review by hewigovens — COMMENTED** [review]
Since there are too many changes (inside both wallet core and trezor crypto) and we don't have a plan to add windows support for Trust, we suggest you to have a standalone repo `wallet-core-windows` and CI enabled

We will happy to list it on wallet core readme, thanks

**Comment by kaetemi** [comment]
Alright. I was just bulldozing through the warnings earlier to find out if any of those were causing the test failures in FIO. It shouldn't be this many changes once I clean this series up.

I did find a couple of buffer overruns occurring in the test suite, so I'll make a separate PR for those in a bit.

**Comment by kaetemi** [comment]
```
[----------] Global test environment tear-down
[==========] 1462 tests from 313 test suites ran. (17363 ms total)
[  PASSED  ] 1462 tests.
```

**Comment by kaetemi** [comment]
https://github.com/trustwallet/wallet-core/pull/1757

**Pull request closed without merging**
