### PR TITLE
TOP blockchain support

### PR DESCRIPTION
**Pull request by hench-ye**
Description
add TOP blockchain. https://www.topnetwork.org/   https://github.com/telosprotocol

Testing instructions
unit test. TopAddress*, TopSigner*, TopTransaction*, TWAnySignerTop*, TWTopCoinType*
tools/android-test
tools/ios-test

Types of changes
New feature (non-breaking change which adds functionality)

Checklist
* TOP blockchain has launched main net since 11/08/2019 without major security incidents.  Please refer to https://www.topscan.io/en-US .
* TOP blockchain has extensive public documentation: https://developers.topnetwork.org/ . Tools can be downloaded from https://github.com/telosprotocol/TOP-chain/releases/download/v1.1.4/topio-1.1.4-release.tar.gz .  
* https://coinmarketcap.com/currencies/top/  We currently rank 883.
* TOP provide API/JSON-RPC access to the node with a load balancing. Please refer to http://developers.topnetwork.org/en/Interface/RPC-API/Overview/ for detailed information.
* TOP can be traded on Huobi, Bithumb and Hotbit.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Note: for reference, prev draft #1473 .

**Comment by hench-ye** [comment]
Hi Adam, I have answered checklist question above. What should I do something else?  Thanks.

**Comment by catenocrypt** [comment]
Thanks for the input.  Please be patient until we evaluate TOP chain inclusion.

**Comment by catenocrypt** [comment]
Sorry, we reject inclusion right now, the project usage is still marginal, well below our published integration criteria guidelines.
https://developer.trustwallet.com/wallet-core/newblockchain
Closing.

**Comment by hench-ye** [comment]
Hi Adam, can you tell me what is the main reason why we can not pass the criteria? Is it that we currently only rank 883 on the CainMarketCap ?

**Comment by hench-ye** [comment]
Hi Adam, can you tell me what is the main reason why we can not pass the criteria? Is it that we currently only rank 883 on the CainMarketCap ?

**Pull request closed without merging**
