### PR TITLE
Replace string to string_view in the functions arguments

### PR DESCRIPTION
**Pull request by safocl**
## Description

`const std::string&` is aka `const char*&`, is an extra level of transition on the pointer.
`std::string_view` aka `const char*` solves that trouble.

## How to test
it is described in the standard с++17 and later.

## Types of changes
replace `const std::string&` to `std::string_view` in the function arguments.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Compile errors; TW::Data should be extended to take also string_view argument.

**Comment by safocl** [comment]
> Compile errors; TW::Data should be extended to take also string_view argument.

i don't check immediately errors on my computer with archlinux -- cmake configs in this project don't find required libs and tools on my system. But initiate with external downloading of the dependencies is very long time.

**Comment by safocl** [comment]
> Compile errors; TW::Data should be extended to take also string_view argument.

trust-wallet-core/src/Data.h contain `using TW::Data = std::vector<byte>` and one of the variants `data()` function has `inline Data data(std::string_view data) {
    return Data{data.begin(), data.end()};
}` implementation.
With it TW::Data should be created with `std::string_view` instead `const std::string&`

**Comment by Milerius** [comment]
We should absolutely not merge this, string_view are not null terminated and can lead to terrible bugs - refusing the pr as now.

**Comment by Milerius** [comment]
> We should absolutely not merge this, string_view are not null terminated and can lead to terrible bugs - refusing the pr as now.

For ref: https://quuxplusone.github.io/blog/2020/03/20/c-str-correctness/#:~:text=By%20design%2C%20string_view%20is%20not,with%20these%20C%20library%20functions.

As of now this is too risky to merge such change.

**Comment by safocl** [comment]
> We should absolutely not merge this, string_view are not null terminated and can lead to terrible bugs - refusing the pr as now.

string_view can keep either null-terminated or not null-terminated string -- if source string for the function argument has null-terminator -- string_view as the function in-argument will be null-terminator also.

**Comment by safocl** [comment]
> > We should absolutely not merge this, string_view are not null terminated and can lead to terrible bugs - refusing the pr as now.
> 
> string_view can keep either null-terminated or not null-terminated string -- if source string for the function argument has null-terminator -- string_view as the function in-argument will be null-terminator also.
> 
> upd. onli the c_str() as a std::string method has guarantee for null-terminator vs the data() as a std::string_view method that not has guarantee for null-terminator

also std::string has constructor from stringViewLike entity.
`template< class StringViewLike >explicit constexpr basic_string( const StringViewLike& t,                                 const Allocator& alloc = Allocator() ); | (since C++20)`

**Comment by safocl** [comment]
> > > We should absolutely not merge this, string_view are not null terminated and can lead to terrible bugs - refusing the pr as now.
> > 
> > 
> > string_view can keep either null-terminated or not null-terminated string -- if source string for the function argument has null-terminator -- string_view as the function in-argument will be null-terminator also.
> > upd. onli the c_str() as a std::string method has guarantee for null-terminator vs the data() as a std::string_view method that not has guarantee for null-terminator
> 
> also std::string has constructor from stringViewLike entity. `template< class StringViewLike >explicit constexpr basic_string( const StringViewLike& t,                                 const Allocator& alloc = Allocator() ); | (since C++20)`

c++20 draft N4849:
> 21.4 String view classes  [string.view]
> 21.4.1 General                 [string.view.general]
> 1 The class template basic_string_view describes an object that can refer to a constant contiguous sequence
> of char-like (21.1) objects with the first element of the sequence at position zero. In the rest of 21.4, the type
> of the char-like objects held in a basic_string_view object is designated by charT.
> 2 [Note 1 : The library provides implicit conversions from const charT* and std::basic_string<charT, ...> to
> std::basic_string_view<charT, ...> so that user code can accept just std::basic_string_view<charT> as a
> non-templated parameter wherever a sequence of characters is expected. User-defined types can define their own
> implicit conversions to std::basic_string_view in order to interoperate with these functions. — end note]

**Comment by safocl** [comment]
`constexpr basic_string( const CharT* s, const Allocator& alloc = Allocator() );`
> Constructs the string with the contents initialized with a copy of the null-terminated character string pointed to by s. The length of the string is determined by the first null character. The behavior is undefined if [s, s + Traits::length(s)) is not a [valid range](https://en.cppreference.com/w/cpp/iterator#Ranges) (for example, if s is a null pointer). This constructor is not used for [class template argument deduction](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction) if the Allocator type that would be deduced does not qualify as an allocator. (since C++17)

it cancels guarantee of null-terminating string in the std::string -- UB if it construct from non null-terminating string.

**Comment by safocl** [comment]
> s

theoretically the string by that constructor can contain null-terminator, but the containing "null-terminating string" will be not valid.

**Comment by safocl** [comment]
ci/cd reports:
```
/home/runner/work/wallet-core/wallet-core/src/Tron/Signer.cpp:156:10: fatal error: no viable conversion from 'decltype(__cont.data())' (aka 'const char *') to 'TW::Data' (aka 'vector<unsigned char>')
    Data amount = data(transferTrc20Contract.amount());
         ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
but ```
Data data(std::string_view data) {
    return Data{data.begin(), data.end()};
}
```

**Comment by safocl** [comment]
for example: https://godbolt.org/z/vx1YdYca3
```
#include <iostream>
#include <string>

int main() {
    const char * c0 = "fdsa";
    auto c1 = const_cast<char*>(c0);
    c1[4]='\0';
    
    std::string s{c0};

    std::cout << s << std::endl;
    
    return 0;
}
```

**Comment by safocl** [comment]
> for example: https://godbolt.org/z/vx1YdYca3
> 
> ```
> #include <iostream>
> #include <string>
> 
> int main() {
>     const char * c0 = "fdsa";
>     auto c1 = const_cast<char*>(c0);
>     c1[4]='\0';
>     
>     std::string s{c0};
> 
>     std::cout << s << std::endl;
>     
>     return 0;
> }
> ```
> 
> and https://godbolt.org/z/YhhnWrEMq `c1[4]='a' instead;`
> 
> and https://godbolt.org/z/o7Mjzhvqh shows cancel guarantee for null-terminating string by c_str() method.
> 
> but if comment `//c1[4]='a';` -- will be ok;

it's prove identically behavior any of std::string or std::string_view as the function argument for the null-terminating strings.

**Comment by safocl** [comment]
c++ standard provide guarantee only the literal string for null-terminating really

**Comment by safocl** [comment]
> ci/cd reports:
> 
> ```
> /home/runner/work/wallet-core/wallet-core/src/Tron/Signer.cpp:156:10: fatal error: no viable conversion from 'decltype(__cont.data())' (aka 'const char *') to 'TW::Data' (aka 'vector<unsigned char>')
>     Data amount = data(transferTrc20Contract.amount());
>          ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> but
> 
> ```
> Data data(std::string_view data) {
>     return Data{data.begin(), data.end()};
> }
> ```
> 
> and `using Data = std::vector<byte>;`

i'm finding of that trouble -- it uses the data() function overloading not TW::data()

**Comment by Milerius** [comment]
> > ci/cd reports:
> > ```
> > /home/runner/work/wallet-core/wallet-core/src/Tron/Signer.cpp:156:10: fatal error: no viable conversion from 'decltype(__cont.data())' (aka 'const char *') to 'TW::Data' (aka 'vector<unsigned char>')
> >     Data amount = data(transferTrc20Contract.amount());
> >          ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but
> > ```
> > Data data(std::string_view data) {
> >     return Data{data.begin(), data.end()};
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and `using Data = std::vector<byte>;`
> 
> i'm finding of that trouble -- it uses the data() function overloading not TW::data() -- need use TW::data() instead.

Maybe due to https://en.cppreference.com/w/cpp/language/adl

**Review by hewigovens — COMMENTED** [review]
Need to fix the CI

**Comment by Milerius** [comment]
Closing, feel free to re-open if u rework on this PR

**Pull request closed without merging**
