### PR TITLE
Hotfix for Dash p2sh address

### PR DESCRIPTION
**Pull request by hewigovens**
1. add lock script tests for dash / qtum
2. revert MUE and cleanup

### CODE REVIEW

**Comment by vikmeup** [comment]
@hewigovens can you rebase and let's get this merged into master

**Comment by sotblad** [comment]
Hey, may I ask why MUE got removed from the code? Thanks

**Comment by hewigovens** [comment]
This was an urgent hotfix and caused by merging MUE which p2pkh prefix is duplicated with dash p2sh prefix

**Comment by sotblad** [comment]
> This was an urgent hotfix and caused by merging MUE which p2pkh prefix is duplicated with dash p2sh prefix

Is there any way this can be fixed and get MUE merged again?

**Comment by sotblad** [comment]
MUE's p2pkh prefix is the same as Dash's p2sh prefix and reverse.
Please let me know, we would really love to have MUE on TrustWallet.
Thanks.

**Comment by hewigovens** [comment]
we understand, we have revised our [requirements](https://developer.trustwallet.com/wallet-core/newblockchain#requirements) recently, we will be very careful when adding new coins, especially bitcoin fork

**Pull request merged**
