### PR TITLE
Add -fno-aligned-allocation to Podspec

### PR DESCRIPTION
**Pull request by dstranz**
## Description

This PR adds fix applied by @alejandro-isaza for not compatible "aligned allocation"  https://github.com/TrustWallet/wallet-core/commit/b1b876baa123cb7a7ca3cb52b7fd22246ad88e1d also to static Podspec file. 

Previously this flag `-fno-aligned-allocation` was added only to ios.toolchain.cmake that is not used in case when we have TrustWalletCore pod installed directly from GitHub, like:
`pod 'TrustWalletCore', :git => 'git@github.com:TrustWallet/wallet-core.git', :branch => 'master'`

Without proposed change, it's not possible to archive successfully the project. It finishes with a lot of similar errors:
```
Pods/TrustWalletCore/src/interface/TWBitcoinTransactionSigner.cpp:24:12: aligned allocation function of type 'void *(unsigned long, enum std::align_val_t)' is only available on iOS 11 or newer

return new TWBitcoinTransactionSigner{ TransactionSigner<Transaction>(std::move(input)) };
    ^~~
```

## Testing instructions

Use TrustWalletCore declaration GitHub source:
`pod 'TrustWalletCore', :git => 'git@github.com:TrustWallet/wallet-core.git', :branch => 'master'`

Try to archive the project with and without the fix.

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.

### CODE REVIEW

**Comment by hewigovens** [comment]
We're using master branch `TrustWalletCore.podspec` in Trust and don't have this issue

**Comment by dstranz** [comment]
@hewigovens Maybe you add this `-fno-aligned-allocation` declaration manually to Build Settings?

**Comment by hewigovens** [comment]
Have you tried to set iOS deployment to 11.0? I don't think we want to support iOS 10 anymore, Apple  will introduce new iOS in forthcoming WWDC.

**Comment by vikmeup** [comment]
@hewigovens +1

**Comment by dstranz** [comment]
@hewigovens If you have deployment target set to 11.0 - that's probably the reason why it works.

**Comment by dstranz** [comment]
Zrzut ekranu 2019-05-31 o 14 06 41

I've checked that on empty project and confirmed that it doesn't work without this change or dropping iOS 10 support ;)

...but then it may be better to change that also in Podspec files ;)

**Comment by hewigovens** [comment]
Ok, I will test it tomorrow

**Comment by dstranz** [comment]
To be clear - I'm also open to dropping iOS 10 support. But IMHO it's good to be consistent with that - support iOS 10 everywhere or remove from podspec.

**Comment by hewigovens** [comment]
@dstranz Hi, we decide to remove iOS 10 support, I will open a pr shortly, that's a bit weird why Trust works (it shouldn't).

**Comment by hewigovens** [comment]
Thanks for your report, let's close this now

**Pull request closed without merging**
