### PR TITLE
Support for Steem

### PR DESCRIPTION
**Pull request by bravoadam**
## Description

Adds support for [Steem](https://steem.com/) blockchain. We have reused a lot of Bravo's code to add the support, thanks to their similarities.

## Testing instructions

We have added tests in src/tests as well as swift and kotlin tests in their respective directories

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [ ] Update documentation as needed.

### CODE REVIEW

**Comment by srpatel19590** [comment]
we have noticed indentation issues in `src/Coin.cpp` and `src/interface/TWCoinTypeConfiguration.cpp` files. we will fix it together with review changes if any.

**Comment by alejandro-isaza** [comment]
Looks good other than indentation.

**Comment by srpatel19590** [comment]
@alejandro-isaza Not sure about the CI status "Waiting for status to be reported". Do we need to rebase again?

**Comment by hewigovens** [comment]
CI is not triggered somehow, and we refactor a bit on master, could you please rebase and fix the indentation?

**Comment by bravoadam** [comment]
Indentation is fixed. Let me rebase again.

**Comment by srpatel19590** [comment]
@alejandro-isaza we rebased again but for some reason, CI is not spinning up.

**Comment by srpatel19590** [comment]
@hewigovens It is done. can you please merge if everything is okay. we will raise another for EOS after merge.

**Pull request merged**
