### PR TITLE
Revert InputSelector.cpp until further research

### LINKED ISSUE #2344: Big BUG : network fee change
Hi,
why network fee change after transfer confirm?

photo_2022-06-27_14-33-45
photo_2022-06-27_14-33-51

### PR DESCRIPTION
**Pull request by Milerius**
## Description

Revert for: #2344 , introduced in https://github.com/trustwallet/wallet-core/pull/2305

## How to test

run unit tests

## Types of changes

Should fix #2344 will re-open the improvements as a draft for further research

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by hewigovens — APPROVED** [review]

**Comment by nonomaxxis** [comment]
Hello, great.
What happens to these coins that are lost in this bug?
Does it go back to the wallet?
Do I have to do something?

**Comment by nonomaxxis** [comment]
@hewigovens , @Milerius.
Hello, great.
What happens to these coins that are lost in this bug?
Does it go back to the wallet?
Do I have to do something?

**Comment by hewigovens** [comment]
@nonomaxxis we will reimburse your loss, 100 DOGE, is that number correct?

**Comment by nonomaxxis** [comment]
> @nonomaxxis we will reimburse your loss, 100 DOGE, is that number correct?

Yes that's correct.

**Comment by hewigovens** [comment]
Ok, would you like to receive it on `DSpDKw6wdnrnxZBtAEn1txYSqPb5uMmxXp` or a new address?

**Comment by nonomaxxis** [comment]
Yes, address is correct.

**Comment by nonomaxxis** [comment]
> Ok, would you like to receive it on `DSpDKw6wdnrnxZBtAEn1txYSqPb5uMmxXp` or a new address?

Yes, address is correct.

**Comment by hewigovens** [comment]
Done in https://blockchair.com/dogecoin/transaction/ec85672c742810866fc9253ee0fdfaf17109d79d079ab3aaa72716988c15800a?from=trustwallet

**Pull request merged**
