### PR TITLE
Ronin accepts & normalizes Eth address as well

### LINKED ISSUE #2236: [Ronin] Support both 0x / ronin prefix in AnyAddress

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Fixes #2236

## Checklist

- [ ] Create pull request as draft initially, unless its complete.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by hewigovens — APPROVED** [review]

**Comment by hewigovens** [comment]
@catenocrypt https://github.com/trustwallet/wallet-core/blob/master/src/Ethereum/Signer.cpp#L115 this can be removed too

**Comment by catenocrypt** [comment]
> @catenocrypt https://github.com/trustwallet/wallet-core/blob/master/src/Ethereum/Signer.cpp#L115 this can be removed too

I don't think so, because there Ethereum::Address is used, which is not modified, so it will not accept `ronin:` address.

**Comment by catenocrypt** [comment]
I am still hesitant to merge this, want to understand the root cause better, because with this change we just give up the point of a prefix, to reduce the risk of mixing up addresses.  To be able to normalize, the non-prefix version also has to be accepted as valid.

**Comment by hewigovens** [comment]
Let's see if we can fix assets repo instead

**Comment by hewigovens** [comment]
I attempted to change the token address in the assets repo, but it turns out that only Linux supports file names that contain ':', which may result in some breaking changes to the backend / assets api.

**Pull request merged**
