### PR TITLE
[Wasm] Enable strict build mode and disable `eval`

### PR DESCRIPTION
**Pull request by hewigovens**
## Description

Chrome Extension Manifest v3 and Vitejs production build disable ` unsafe-eval`, trying to fix https://github.com/trustwallet/wallet-core/issues/2429 as well.

Changes:
- strict build mode and safer optimization level -O2
- enable `MODULARIZE` and adjust all the tests
- fix `wallet-core.d.ts`

## How to test

- Build and unit test
- Test react / vitejs sample

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

### CODE REVIEW

**Review by catenocrypt — APPROVED** [review]

**Review by Milerius — APPROVED** [review]

**Comment by berniceburgo** [comment]
Trust wallet I am here Bernice burgos
5AD9806A-CE02-4DFD-A7B7-0C10052518AA

**Comment by berniceburgo** [comment]
Please set it am using different email and password

**Comment by berniceburgo** [comment]
I changed it back to trust wallet now

**Review by Milerius — APPROVED** [review]

**Comment by trastvolt** [comment]
h/wasm-fix

**Comment by trastvolt** [comment]
h/wasm-fix

**Pull request merged**
