### PR TITLE
[Breaking] Remove AnySigner

### PR DESCRIPTION
**Pull request by hewigovens**
It's hard to construct correct raw json string (not type safe either), will be replaced by TrustSDK and native interaction (not web)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Could you double check that removed AnySigner tests are covered by other coin-specific signer tests?

**Comment by catenocrypt** [comment]
Could you double check that removed AnySigner sample calls have there matching coin-specific signer calls (EthSigner)?

**Comment by catenocrypt** [comment]
On hold until end of Jan, release native staking first for all coins.

**Comment by hewigovens** [comment]
close for now, will push new pr

**Pull request closed without merging**
