### PR TITLE
[ZkSync]: Add support for ZkSync V2 mainnet

### PR DESCRIPTION
**Pull request by miloserdow**
## Description

We currently support zkSync v2 testnet, this PR changes zkSync to mainnet.

## How to test

Unit tests

## Checklist
- [X] Update existing tests and registry

### CODE REVIEW

**Review by hewigovens — APPROVED** [review]

**Comment by hewigovens** [comment]
hmm, Linux CI failed

**Comment by hewigovens** [comment]
I think you only need to add one L2 transfer test or L2 -> test

**Review by Milerius — COMMENTED** [review]
Thanks for the PR, few things:

- Unit tests is failing on linux
- There is no link to the mainnet transaction in the unit test.
- Can you also add a simple L2<->L2 transfer tx please?

**Review by hewigovens — DISMISSED** [review]

**Review by catenocrypt — CHANGES_REQUESTED** [review]
- In the registry.json there is no sample (real) tx and address fields, please add some
- Why did you remove the signer tests, not update them?

**Comment by miloserdow** [comment]
Sorry, this should've been a draft PR - I'm still waiting for alpha/beta mainnet launch as now it's restricted to zkSync devs only.

**Comment by SUPPORTTEAMHERR** [comment]
> Sorry, this should've been a draft PR - I'm still waiting for alpha/beta mainnet launch as now it's restricted to zkSync devs only.

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Review by Milerius — APPROVED** [review]
EVM unit tests will be added to wallet kit, 100% compatible as other EVM chains, should be smooth.

**Review by hewigovens — APPROVED** [review]

**Pull request merged**
