### PR TITLE
[Bitcoin/Rust]: Finalize Bitcoin V2 refactoring

### PR DESCRIPTION
**Pull request by satoshiotomakan**
## Types of changes

Introduce an improved Bitcoin transaction signing, address derivation in Rust.

### BitcoinV2 improvements

* `AnySigner.plan` - used to estimate the transaction size, fee, change, ...
* `TransactionCompiler.preImageHashes` and `TransactionCompiler.compile` - used for external signing with signatures verification
* `OP_RETURN` for ThorChainSwap
* 

For more examples, see iOS and Android tests.

### BREAKING CHANGES

* Remove chain name from the TWDerivation enum variants
For example, `TWDerivationLitecoinSegwit` becomes `TWDerivationSegwit`
* Add explicit derivations to registry.json for Bitcoin chains
* Refactor `BitcoinV2.proto` API significantly
* Remove `TWBitcoinFee` module
* Remove `TWBitcoinFeeCalculateFee`, `TWBitcoinScriptBuildBRC20InscribeTransfer`, `TWBitcoinScriptBuildOrdinalNftInscription`
* Remove `Bitcoin.Proto.SigningInput.is_it_brc_operation` and `Bitcoin.Proto.SigningInput.planning_v2`

### Other changes

* Add `Schnorr` key-pair (in Rust only)

### TODO next iteration

- [ ] TODO comments (small improvements)
- [ ] Expose `Schnorr` private and public key functions via FFI
- [ ] Add fuzz testing
- [ ] Add support for P2SH, P2WSH spending scripts

## Checklist

- [ ] Create pull request as draft initially, unless its complete.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by Saintloxx — COMMENTED** [review]
Hby and

**Comment by harshavnaik** [comment]
When this PR is planned to merge?

**Review by Lynieya4040 — COMMENTED** [review]
check file showed the change and was marl with a check saying done

**Comment by Mariuszok12** [comment]
> ## Description
> ## How to test
> ## Types of changes
> ## Checklist
> * [ ]  Create pull request as draft initially, unless its complete.
> * [ ]  Add tests to cover changes as needed.
> * [ ]  Update documentation as needed.
> * [ ]  If there is a related Issue, mention it in the description.
> 
> If you're adding a new blockchain
> 
> * [ ]  I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.
bc1p8eedmn7ejreey6kt0nttxu7jkt9gsxjs4ghtjt3cr09awn7k92fqqgveuy

**Review by Milerius — DISMISSED** [review]

**Pull request merged**
