### PR TITLE
Support building for Windows under Visual Studio

### PR DESCRIPTION
**Pull request by kaetemi**
## Description

Support building for Windows under Visual Studio.

### Requirements
* Visual Studio 2022
* CMake
* Ruby

### Build

```
powershell .\tools\windows-dependencies.ps1
powershell .\tools\windows-generate.ps1
powershell .\tools\windows-build.ps1
powershell .\tools\windows-samples.ps1
powershell .\tools\windows-tests.ps1
```

```
[==========] 1464 tests from 313 test suites ran. (13231 ms total)
[  PASSED  ] 1464 tests.
```

### CODE REVIEW

**Review by hewigovens — COMMENTED** [review]
Nice work, As I said early(also needs to periodically sync trezor code), could you setup another repo and add windows CI? we're happy to list it on this repo's readme

**Comment by catenocrypt** [comment]
As explained, we will not merge Win support into mainline as of now.  If there are parts of it which are not very Windows specific, not very high impact, consider creating different PRs with them.

**Comment by catenocrypt** [comment]
Any more simple parts of this PR that is worth consider separately?

**Comment by hewigovens** [comment]
Added to readme: https://github.com/trustwallet/wallet-core#community

**Pull request closed without merging**
