### PR TITLE
Move BinaryCoding.h and add big-endian support

### PR DESCRIPTION
**Pull request by terorie**
* Moves `src/Bitcoin/BinaryCoding.h` to `src/BinaryCoding.h`
 * Renames all functions to `<encode/decode><16/32/64><LE/BE>`

### CODE REVIEW

**Comment by alejandro-isaza** [comment]
Seems like you missed some spots and the tests failed.

**Comment by terorie** [comment]
@alejandro-isaza My bad, I missed an import. The CI is still failing, but I think this is not my fault.

**Comment by alejandro-isaza** [comment]
Looks like a glitch. Can you try rebasing on latest master.

**Comment by terorie** [comment]
Done. I'll also run the tests locally, Bitrise is a bit slow.

**Comment by terorie** [comment]
@alejandro-isaza It passed 🍾

**Comment by terorie** [comment]
@hewigovens Fixed in #85

**Comment by hewigovens** [comment]
Thanks @terorie !

**Pull request merged**
