### PR TITLE
Update go samples

### LINKED ISSUE #1841: How to update wallet-core inside docker image
**Describe the bug**
When I clone the project and run these steps:
```
./bootstrap.sh
./tools/generate-files
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
make -Cbuild
```

and after that try to run or build my (golang) project then throws lots of errors like:

```
/wallet-core/build/libTrustWalletCore.a(Entry.cpp.o): In function `__cxx_global_var_init':
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/iostream:74: undefined reference to `std::ios_base::Init::Init()'
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/iostream:74: undefined reference to `std::ios_base::Init::~Init()'
/wallet-core/build/libTrustWalletCore.a(Entry.cpp.o): In function `TW::Cosmos::Address::isValid(TWCoinType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/wallet-core/src/Cosmos/Address.h:40: undefined reference to `std::allocator<char>::allocator()'
/wallet-core/src/Cosmos/Address.h:40: undefined reference to `std::allocator<char>::~allocator()'
```

while before pulling the new version of codes, everything was ok.

also, I cloned the code and build it on Mac but now how can I use it in my **GoLang** project?

### PR DESCRIPTION
**Pull request by apm-dev**
## Description

Update and Add more samples of using wallet-core functionalities in Go.
* Bitcoin, Ethereum, Tron wallet creation.
* Btc, Eth transaction creation.
* Add sample for some other methods of TWCoinType, TWCoinTypeConfiguration, TWHDWallet, TWMnemonic, ...
* Restructure and move the codes that talk to wallet-core to a separate package and make the main file cleaner.

Fixes #1841 

## Testing instructions

Like before, described in readme.

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

* New feature (non-breaking change which adds functionality)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

@hewigovens

### CODE REVIEW

**Review by hewigovens — COMMENTED** [review]
Nice work!, can we reuse `proto` files in `src/proto` and generate `Bitcoin.pb.go` and other files in a script?

**Comment by apm-dev** [comment]
> Nice work!, can we reuse `proto` files in `src/proto` and generate `Bitcoin.pb.go` and other files in a script?

Thanks, I think yes but not that easy, it would better if we add `go_package='...'` to `src/proto` files. cos **protoc-gen-go** can't generate easily without that.
I put the command which I compile proto files with inside `compile.sh`.

**Comment by hewigovens** [comment]
@apm-dev I think we can copy the protos to from src to go sample folder in `compile.sh`, just don't check in duplicate proto file and pb.go

**Comment by apm-dev** [comment]
> @apm-dev I think we can copy the protos to from src to go sample folder in `compile.sh`, just don't check in duplicate proto file and pb.go

Could you explain in more detail, please?
What should I do now?
* writing bash script inside `compile.sh` to copy `.proto` files from `src/proto` and then compile them inside go-sample?
* or updating the `tools/generate-files` bash script to generate also go protobuf files?

**Comment by hewigovens** [comment]
@apm-dev Yes, "writing bash script inside compile.sh to copy .proto files from src/proto and then compile them inside go-sample", I can do it later for you if you prefer

**Comment by apm-dev** [comment]
It's OK, I'll do that, Thanks.

**Comment by apm-dev** [comment]
@hewigovens Hi, compile.sh completed, now we can run `./compile.sh` and all the required proto files in `src/proto` will be generated inside `protos` folder.

**Review by catenocrypt — APPROVED** [review]

**Comment by apm-dev** [comment]
Yes, I delete others and put them just for example.
I will add an step about generating proto files in readme.

**Comment by catenocrypt** [comment]
heads up @apm-dev , I've created a PR #1864 to add building of Go sample app to CI, plus do some fixes to the Go sample app.  I also updated the Dockerfile with Go to be able to build sample app inside docker.
Please have a look, I think the fixes you already did in this PR as well.

**Comment by apm-dev** [comment]
> heads up @apm-dev , I've created a PR #1864 to add building of Go sample app to CI, plus do some fixes to the Go sample app. I also updated the Dockerfile with Go to be able to build sample app inside docker. Please have a look, I think the fixes you already did in this PR as well.

Hi @catenocrypt , I saw that and I think we worked on two different contexts, this PR is about adding some new samples of using TW by golang with some improvements, and #1864 is about fixing some imports and modifying some CI and docker parts.
I think these two PRs can merge together.

**Comment by catenocrypt** [comment]
> Hi @catenocrypt , I saw that and I think we worked on two different contexts, this PR is about adding some new samples of using TW by golang with some improvements, and #1864 is about fixing some imports and modifying some CI and docker parts. I think these two PRs can merge together.

There were some overlapping changes, like TWMnemonic include or -lc++, non-trivial merge, but I have resolved them in #1864 (as this PR has been merged in the meantime)

**Comment by arslan-raza-143** [comment]
> > Hi @catenocrypt , I saw that and I think we worked on two different contexts, this PR is about adding some new samples of using TW by golang with some improvements, and #1864 is about fixing some imports and modifying some CI and docker parts. I think these two PRs can merge together.
> 
> 
> 
> There were some overlapping changes, like TWMnemonic include or -lc++, non-trivial merge, but I have resolved them in #1864 (as this PR has been merged in the meantime)
> 
> 

@apm-dev

**Pull request merged**
