### PR TITLE
[WIP] add conan dependencies

### PR DESCRIPTION
**Pull request by stracedude**
## Description

Manage internal dependencies with conan. #977 

- gtest/1.8.1
- nlohmann_json/3.7.0
- protobuf/3.9.1
- boost/1.74.0

## Testing instructions
```
tools/generate-files
conan install -if build --profile=conan/profile .
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
make -Cbuild -j12 tests TrezorCryptoTests
```

## Types of changes

* New feature (non-breaking change which adds functionality) 

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

**Comment by hewigovens** [comment]
`tools/install-dependencies` failed, we need to build two protobuf plugins

**Comment by catenocrypt** [comment]
I'm trying to make this work #1109 .  Protobuf building is put back, but currently I have some issues with installing conan itself.

```
 Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 PyJWT-1.7.1 PyYAML-5.3.1 bottle-0.12.18 certifi-2020.6.20 chardet-3.0.4 colorama-0.4.3 conan-1.29.2 deprecation-2.0.7 distro-1.5.0 fasteners-0.15 future-0.18.2 idna-2.10 monotonic-1.5 node-semver-0.6.1 packaging-20.4 patch-ng-1.17.4 pluginbase-1.0.0 pygments-2.7.1 pyparsing-2.4.7 python-dateutil-2.8.1 requests-2.24.0 six-1.15.0 tqdm-4.49.0 urllib3-1.25.10
/home/runner/work/_temp/93f1c9f0-4c3c-4f40-a9f3-1739a0a8ad34.sh: line 8: conan: command not found
```

**Comment by stracedude** [comment]
@catenocrypt Sorry for the long answer, the problem is in the canon installation path. I'm trying to resolve this issue.

**Comment by stracedude** [comment]
@catenocrypt @hewigovens Why don't you use cmake to xcode build ? Are there any restrictions?
`cmake -G Xcode .. ` should work.

**Comment by hewigovens** [comment]
@stracedude we do compile iOS lib with cmake (see `tools/ios-build`), iOS tests and some other helper classes are in `swift` folder

**Comment by stracedude** [comment]
@hewigovens @catenocrypt 

The problem is that it is not possible to use canon with swift in the current form.

In ios-ci run tools/ios-test, it use project.yml, build protobuf, link json and boost from cpp.xcconfig. I can't embed conan here.

I see 2 ways:

1. add xcode generator in conan, create conanbuildinfo.xcconfig  and use it in project.yml. Simple solution. But I have no experience in this. https://docs.conan.io/en/latest/integrations/ide/xcode.html
2. build the swift framework and its test with cmake. A complex solution, but beautiful - with a single build system. 
https://cmake.org/cmake/help/v3.6/release/3.4.html

**Comment by hewigovens** [comment]
@stracedude let's keep protobuf as it is now? for swift framework, we will adopt swift package manager later, no plan to step back to conan or cmake (so we can try out new apple toolchain easily)

**Comment by catenocrypt** [comment]
Is it possible to keep protobuf as it is for swift, but use conan for C++?  I guess not as both are handled in install-dependencies.

**Comment by stracedude** [comment]
@hewigovens @catenocrypt  Yes, I think it will work, need to make the build stages independent. I will try to do this in the next few days.

**Comment by khokho1986** [comment]
<3AhLfoVCK1UcA8VjCDu6r1ZQTLEdVq3LPc>

**Review by kaycoinsUSA — APPROVED** [review]

**Comment by catenocrypt** [comment]
Summarizing the status:

- Which pkgs can be managed with conan?
boost, nlohman_json, gtest, and protobuf <-- last one is questionable

- How often did we update them?  Maybe once per year each; update is likely imposing other changes even if managed with conan

- What extra dependencies are needed in the development environment?
Python (not used so far), conan.

- Other issues
Integrating in iOS pipeline

--> Looking at the costs (ios issues, extra deps) and benefits (smoother dependency version update) I would skip this for now.  Open for discussion, @hewigovens , @stracedude .

**Comment by hewigovens** [comment]
let's skip this then, we might need a simple script to check latest versions of our dependencies

**Pull request closed without merging**
