### PR TITLE
LUX clean addition

### PR DESCRIPTION
**Pull request by giaki3003**

### CODE REVIEW

**Comment by hewigovens** [comment]
Hi, can you fix CI?

**Comment by giaki3003** [comment]
> Hi, can you fix CI?

Hey, Ci is broken from an Ontology unit test. Not lux related

**Comment by hewigovens** [comment]
hmm, that's weird, Ontology unit test is passed on master  https://dev.azure.com/TrustWallet/Trust%20Wallet%20Core/_build/results?buildId=2620, and we add Swift / Android address derivation test enforcement

**Comment by giaki3003** [comment]
I think I see the issue now. Thanks for pointing it out

**Pull request closed without merging**
