### PR TITLE
Ed25519 support

### PR DESCRIPTION
**Pull request by terorie**
* Move C++ `PrivateKey/PublicKey` to `TW::secp256k1` namespace
 * Append `Secp256k1` to all C symbols related to ECDSA asymmetric crypto
 * Add `TW::ed25519` namespaces and classes
 * Add `TWPrivateKeyEd25519` and `TWPublicKeyEd25519` classes
 * Update JNI/Swift bindings

### CODE REVIEW

**Comment by alejandro-isaza** [comment]
Looks good so far. Missing Swift and Android changes.

**Comment by hewigovens** [comment]
@terorie You may forget to commit `TWPublicKeyEd25519.cpp`?

**Comment by hewigovens** [comment]
Swift part is fixed

**Comment by terorie** [comment]
@hewigovens Yes, I didn't commit `TWPublicKeyEd25519.cpp` because I didn't find the verify function. Why is it named `ed25519_sign_open` 😅

**Comment by hewigovens** [comment]
@terorie you probably not read the readme :)

**Comment by terorie** [comment]
@hewigovens You got me 👀 
Should I rebase this PR on newest master?

**Comment by hewigovens** [comment]
I think it's already merged with master

**Comment by terorie** [comment]
Rebased, first commit contains human changes. Second is code gen

**Pull request merged**
