### PR TITLE
Add support for Viacoin [chain-integration]

### PR DESCRIPTION
**Pull request by romanornr**
## Description

Add support for Viacoin. Chain intergration.

old pull request: https://github.com/TrustWallet/wallet-core/pull/274

## Checklist

- [ ] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [ ] Update documentation as needed.

### CODE REVIEW

**Comment by romanornr** [comment]
I just force pushed a commit.

used 

git -A
git commit -S --amend
git push -f

Unsure how I can these Azure tests running

**Comment by romanornr** [comment]
CI fixed

**Comment by hewigovens** [comment]
We have added codecov recently, could you please fix test coverage? Thanks

**Comment by alejandro-isaza** [comment]
Please add tests to CoinTests.cpp, that should fix the Codecov failure.

**Comment by romanornr** [comment]
Will work on it.

**Comment by alejandro-isaza** [comment]
This should fix it: https://github.com/TrustWallet/wallet-core/commit/fc98868134ccda04a2ee57905e21b9285b9e307a

**Comment by romanornr** [comment]
So it's all good now?
Or am I supposed to git cherry pick it and push an extra commit to this pull request? 

Or just edit it in my editor and do git add - A
And git commit -S --amend? 

Or can this pull request be merged now?

**Comment by alejandro-isaza** [comment]
Please rebase on latest master.

**Comment by romanornr** [comment]
Oke I just rabased. 
CI tests are running (build #2401 if I'm right)

**Comment by romanornr** [comment]
Codecov still fails

**Comment by vikmeup** [comment]
@romanornr can you DM me on telegram @vikmeup, I would need a blockbook url node from you.

**Pull request merged**
