### PR TITLE
Kiko

### PR DESCRIPTION
**Pull request by abbaskiko**
## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [ ] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).
Thx

### CODE REVIEW

**Comment by catenocrypt** [comment]
I think this is a misake.
What is the purpose, please describe.
Way too  many changed files.
Why target branch is my Solana branch?
Closing.

**Comment by abbaskiko** [comment]
hi dear adam
perhaps i dont know exactly about that
im a new and no experience in code programer i just read some and run it
testing
so can you explain pls to me target branch.? what is that if is
different ?? so if the target is solana or i dont know is a town or what ?

**Comment by catenocrypt** [comment]
What are you trying to achieve?

**Comment by abbaskiko** [comment]
i try to get some tokern or something else but i cant

**Pull request closed without merging**
