### PR TITLE
[ZelCash] Flux Rebrand

### PR DESCRIPTION
**Pull request by XK4MiLX**
## Description
Rebrant Zelcash (Zel) to Flux

Change list:
- new explorer
- new symbol
- new name
- new url

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please also create a PR for the assets repository (file blockchains/zelcash/info/info.json, folder can be renamed).
For `name` we should keep the old value, as various code elements are generated from it.

**Comment by vikmeup** [comment]
@catenocrypt let's keep ID as is, or it could break things. 

Name should stay as is, but use preferredName field instead, as we did for bnb and couple of others

**Comment by XK4MiLX** [comment]
i already created pr for blockchains/zelcash/info/info.json it was merged but i set there name Flux

**Comment by Cabecinha84** [comment]
Hello Trust Wallet team. I have updated the tests because they were failing, but they continue to fail, but none information is given, can you help us? Thank you.

**Comment by vikmeup** [comment]
> Hello Trust Wallet team. I have updated the tests because they were failing, but they continue to fail, but none information is given, can you help us? Thank you.

```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TWZelcashCoinType.TWCoinType

 1 FAILED TEST
Error: Process completed with exit code 1.
```

This is the error in the CI

**Review by hewigovens — APPROVED** [review]

**Comment by Cabecinha84** [comment]
Thanks @vikmeup I think it's all good now.
Cheers!

**Review by vikmeup — APPROVED** [review]

**Pull request merged**
