### PR TITLE
RLP long list decoding fix

### LINKED ISSUE #1540: RLP decodeLength error
Hi, I would like to report a RLP decode error. This is my unit test code. RLP decode would report error "length below 56 must be encoded in one byte". I believe there is an error in RLP::decodeLength. Maybe decodeVarInt is misused.
```cpp
    std::string strtemp(300, '9');
    std::string strtemp2(10, '2');
    std::string strtemp3(15, '3');
    auto encoded = Data();
    append(encoded, Ethereum::RLP::encode(strtemp));
    append(encoded, Ethereum::RLP::encode(strtemp2));
    append(encoded, Ethereum::RLP::encode(strtemp3));
    Data output = Ethereum::RLP::encodeList(encoded);
    TW::Ethereum::RLP::DecodedItem decoded = Ethereum::RLP::decode(output);
    
    std::vector<std::string> vecData;
    for (int i = 0; i < (int)decoded.decoded.size(); i++)
    {
        std::string str(decoded.decoded[i].begin(), decoded.decoded[i].end());
        vecData.push_back(str);
        std::cout << "data" << i << ": " << hex(str) << std::endl;
    }
```
This is my version of RLP::decodeLength. It can work correctly. Please take a look.

```cpp
uint64_t RLP::decodeLength(const Data& data) {
    std::string len(data.begin(), data.end());
    std::reverse(len.begin(), len.end());
    if (len.size() == 1)
        return *(uint8_t*)len.c_str();
    else if (len.size() == 2)
        return *(uint16_t*)len.c_str();
    else if (len.size() == 4)
        return *(uint32_t*)len.c_str();
    else if (len.size() == 8)
        return *(uint64_t*)len.c_str();
    throw std::invalid_argument("can't decode length of string/list length");
    return 0;
}
```

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Bug in decoding of strings longer than 256 and lists with over 256 bytes total length.  Fixes #1540.
Also some code readability and tests improvements to RLP.

## Testing instructions

Unit tests, `*RLP*`.

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

**Comment by hewigovens** [comment]
too many unrelated changes, could you please switch to master then a new branch next time?

**Comment by catenocrypt** [comment]
> too many unrelated changes, could you please switch to master then a new branch next time?

PR cleaned up, sorry, I accidentally added a bunch of not-for-commit local files (some mistake with git stash and merge).

**Comment by catenocrypt** [comment]
Only RLP files are affected (h, cpp, test).
First commit contains the fix only.

**Review by hewigovens — APPROVED** [review]
🚀

**Review by vikmeup — APPROVED** [review]

**Pull request merged**
