### PR TITLE
Updated docker build

### PR DESCRIPTION
**Pull request by jlcordeiro**
## Description

Fixes docker build not working due to changes in cmake and recent addition of rust library (([#2706](https://github.com/trustwallet/wallet-core/pull/2706))

## How to test

Run the docker build steps.

## Types of changes

* Updates libssl in the docker container to 1.1.1 as required per the latest version of cmake that ubuntu installs.
* Installs rustc and cargo, which are required after (([#2706](https://github.com/trustwallet/wallet-core/pull/2706)) was merged in.

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

### CODE REVIEW

**Review by Milerius — DISMISSED** [review]

**Review by hewigovens — APPROVED** [review]
Thanks for the fix

**Comment by hewigovens** [comment]
@jlcordeiro can you Lint the Dockerfile?

**Review by catenocrypt — APPROVED** [review]

**Comment by jlcordeiro** [comment]
> @jlcordeiro can you Lint the Dockerfile?

Will do. Warning is about using curl instead of wget (which is what the rest of the Dockerfile uses). Went for that approach as it is the command recommended in wallet-core build docs but will switch to wget.

**Review by catenocrypt — APPROVED** [review]

**Comment by hewigovens** [comment]
Wait until https://github.com/trustwallet/wallet-core/pull/2729 merged, it will fix the Docker build error, @Milerius maybe we should have merged https://github.com/trustwallet/wallet-core/pull/2797

**Review by miloserdow — DISMISSED** [review]

**Comment by hewigovens** [comment]
@jlcordeiro could you please merge master? this should fix Docker CI

**Comment by jlcordeiro** [comment]
> @jlcordeiro could you please merge master? this should fix Docker CI

Done

**Comment by jlcordeiro** [comment]
I am sorry to have to dismiss previously done approvals, but the latest PRs merged on master (https://github.com/trustwallet/wallet-core/pull/2729) broke the build again as there was a missing include <optional> in one of the cpp files.

Added new commit with that.

**Review by Milerius — APPROVED** [review]

**Comment by jlcordeiro** [comment]
@Milerius I believe the failure is because it pulled code before the latest commit which does have the missing include statement thateventually caused the build to fail. 

A fresh run should go through without failures.

**Review by hewigovens — APPROVED** [review]

**Pull request merged**
