### PR TITLE
[XRP] Return sign error tag is invalid

### PR DESCRIPTION
**Pull request by hewigovens**
Fixes https://github.com/trustwallet/wallet-core/issues/1895

### CODE REVIEW

**Review by vikmeup — COMMENTED** [review]
Is it possible to set uint32 on protobuf level?

**Comment by hewigovens** [comment]
@vikmeup Java protobuf represents `uint32` using `int`, I bet Kotlin can do better (https://github.com/trustwallet/wallet-core/issues/1767)

image

from https://developers.google.com/protocol-buffers/docs/proto

**Review by vikmeup — APPROVED** [review]

**Review by catenocrypt — APPROVED** [review]

**Review by SSGoku369 — COMMENTED** [review]
ok

**Comment by SSGoku369** [comment]
ok

**Pull request merged**
