### PR TITLE
Elrond: change the token symbol

### PR DESCRIPTION
**Pull request by andreibancioiu**
## Description

We've changed the token symbol from ERD to eGLD.

## Checklist

- [ ] Prefix PR title with `[WIP]` if necessary.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [ ] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

**Comment by catenocrypt** [comment]
Salut @andreibancioiu : the PR looks OK, but I notice that elrond.com is referring to old symbol `ERD`.  Is this OK?

image

**Comment by andreibancioiu** [comment]
> Salut @andreibancioiu : the PR looks OK, but I notice that elrond.com is referring to old symbol `ERD`. Is this OK?
> 
> image

Salut @catenocrypt! We have to update the site as well - thank you for noticing. In the Blockchain Explorer, we've updated the name: https://explorer.elrond.com/validators.

**Comment by catenocrypt** [comment]
@andreibancioiu , OK.  One more question: the hrp prefix stays "erd", right?

**Comment by andreibancioiu** [comment]
> @andreibancioiu , OK. One more question: the hrp prefix stays "erd", right?

Yes, it stays the same. The addresses will still be like `erd1l453hd0gt5gzdp7czpuall8ggt2dcv5zwmfdf3sd3lguxseux2fsmsgldz`.

**Pull request merged**
