### PR TITLE
Add missing `throw` for EOS transaction

### PR DESCRIPTION
**Pull request by Milerius**
## Description

- fix missing throw according to https://cwe.mitre.org/data/definitions/390.html

### CODE REVIEW

**Review by catenocrypt — APPROVED** [review]

**Comment by catenocrypt** [comment]
EOSTransaction.Serialization failed in test

**Comment by Milerius** [comment]
> EOSTransaction.Serialization failed in test

Yep just saw that, checking now.

**Comment by catenocrypt** [comment]
It has to revisited what format of date is needed, and what is the most reliable way to obtain it.

**Comment by catenocrypt** [comment]
I think the original problem is that 19 is just too small for the result to fit in, changing it to 20 it works fine.
The output string is filled nonetheless, and correct value is used despite the failed check (in this case two bugs cancel out ;D )

**Comment by hewigovens** [comment]
@Milerius could you please write better PR title? not commit style

**Comment by hewigovens** [comment]
Also android CI failed somehow

**Comment by Milerius** [comment]
> I think the original problem is that 19 is just too small for the result to fit in, changing it to 20 it works fine. The output string is filled nonetheless, and correct value is used despite the failed check (in this case two bugs cancel out ;D )

Yes thanks for opening the new PR, I Will travel a lot in the next few days so I will be very busy, I've let a comment on the other pr!

**Pull request closed without merging**
